export const APPLICATION_STATUS = {
  APPLIED: 'APPLIED',
  PHONE_SCREEN: 'PHONE_SCREEN',
  INTERVIEW: 'INTERVIEW',
  TECHNICAL_INTERVIEW: 'TECHNICAL_INTERVIEW',
  FINAL_INTERVIEW: 'FINAL_INTERVIEW',
  OFFER: 'OFFER',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
};

export const STATUS_LABELS = {
  [APPLICATION_STATUS.APPLIED]: 'Applied',
  [APPLICATION_STATUS.PHONE_SCREEN]: 'Phone Screen',
  [APPLICATION_STATUS.INTERVIEW]: 'Interview',
  [APPLICATION_STATUS.TECHNICAL_INTERVIEW]: 'Technical Interview',
  [APPLICATION_STATUS.FINAL_INTERVIEW]: 'Final Interview',
  [APPLICATION_STATUS.OFFER]: 'Offer',
  [APPLICATION_STATUS.REJECTED]: 'Rejected',
  [APPLICATION_STATUS.WITHDRAWN]: 'Withdrawn',
};

export const STATUS_COLORS = {
  [APPLICATION_STATUS.APPLIED]: 'bg-blue-100 text-blue-800',
  [APPLICATION_STATUS.PHONE_SCREEN]: 'bg-yellow-100 text-yellow-800',
  [APPLICATION_STATUS.INTERVIEW]: 'bg-purple-100 text-purple-800',
  [APPLICATION_STATUS.TECHNICAL_INTERVIEW]: 'bg-indigo-100 text-indigo-800',
  [APPLICATION_STATUS.FINAL_INTERVIEW]: 'bg-pink-100 text-pink-800',
  [APPLICATION_STATUS.OFFER]: 'bg-green-100 text-green-800',
  [APPLICATION_STATUS.REJECTED]: 'bg-red-100 text-red-800',
  [APPLICATION_STATUS.WITHDRAWN]: 'bg-gray-100 text-gray-800',
};